# Generated by Django 3.0.8 on 2021-03-29 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-post_date']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='pub_date',
            new_name='post_date',
        ),
    ]
