# Generated by Django 3.0.8 on 2021-03-30 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0002_auto_20210329_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='following',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('followed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_followed', to='clone.Profile')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_following', to='clone.Profile')),
            ],
        ),
    ]
