# Generated by Django 3.0.8 on 2021-03-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0003_auto_20210330_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='image',
            name='following',
        ),
        migrations.AddField(
            model_name='profile',
            name='followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.IntegerField(default=0),
        ),
    ]
